language: go

go:
  - "1.11"
  - "1.12"
  - master

env:
  global:
    - REVIEW_DOG_ON=1.11
    - REVIEW_DOG_VERSION=0.9.11
    - GO111MODULE=on

branches:
  only:
    - master

install:
  - |
    if [ ${TRAVIS_GO_VERSION} == ${REVIEW_DOG_ON} ]; then
      mkdir -p ${GOPATH}/bin
      go get -u golang.org/x/lint/golint
      curl -s -L https://github.com/haya14busa/reviewdog/releases/download/${REVIEW_DOG_VERSION}/reviewdog_linux_amd64 > ${GOPATH}/bin/reviewdog
      chmod +x ${GOPATH}/bin/reviewdog
    fi
script:
  - go build
  - |
    echo "Enable coverage report"
    TEST_ARG="-coverprofile=coverage.txt -covermode=atomic -coverpkg=all"
  - go test ${TEST_ARG} $(go list ./... | grep -v "/examples/")
  - go vet ./...
  - |
    if [ ${TRAVIS_GO_VERSION} == ${REVIEW_DOG_ON} ]; then
      golint ./... | reviewdog -f=golint -reporter=github-pr-review
    fi
after_success:
  - bash <(curl -s https://codecov.io/bash)
