language: go

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - master

branches:
  only:
    - master

install:
  - go get -t ./...
script:
  - go build
  - |
    if [[ ! ${TRAVIS_GO_VERSION} =~ ^1\.(8|9)(\.[0-9]+){0,1}$ ]]
    then
      echo "Enable coverage report"
      REPORT_COVERAGE=1
      TEST_ARG="-coverprofile=coverage.txt -covermode=atomic -coverpkg=all"
    fi
  - go test ${TEST_ARG} ./...
  - go vet ./...
after_success:
  - |
    if [[ ${REPORT_COVERAGE} == 1 ]]
    then
      echo "Reporting coverage"
      bash <(curl -s https://codecov.io/bash)
    fi
